name: Firebase to Excel

on:
  workflow_dispatch:
  schedule:
    - cron: '0 17 * * 3,5'  # Ejecuta miércoles y viernes a las 12 PM hora de Colombia (17:00 UTC)

jobs:
  export-firebase-to-excel:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write  # Necesario para hacer push
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Importante para poder hacer push después
        
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install firebase-admin pandas openpyxl
        
    - name: Create Firebase credentials file
      run: |
        # Método más confiable para crear el JSON
        cat <<EOF > serviceAccountKey.json
        ${{ secrets.FIREBASE_CREDENTIALS }}
        EOF
        
        # Verificación del archivo creado
        echo "=== Contenido del archivo (primeras líneas) ==="
        head -n 5 serviceAccountKey.json
        echo "=== Verificación JSON ==="
        python -c "import json; json.load(open('serviceAccountKey.json')); print('✓ JSON válido')"
      
    - name: Run export script
      run: python firebase_export.py
      
    - name: Commit and push changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add *.xlsx
        git commit -m "Automatic Firebase data update [skip ci]"
        git push
