name: Firebase to Excel

on:
  workflow_dispatch: # Permite ejecución manual
  schedule:
    - cron: '0 8 * * *' # Ejecuta diario a las 8 AM UTC

jobs:
  export-firebase-to-excel:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install firebase-admin pandas openpyxl
        
    - name: Create Firebase credentials file
      run: |
        echo "${{ secrets.FIREBASE_CREDENTIALS }}" > serviceAccountKey.json
        
    - name: Run export script
      id: export
      run: |
        python firebase_export.py
        
    - name: Commit and push changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add firebase_data.xlsx
        git commit -m "Automatic Firebase data update"
        git push