name: Firebase to Excel dos

on:
  workflow_dispatch:
  schedule:
    - cron: '0 8 * * *'  # Ejecuta diario a las 8 AM UTC

jobs:
  export-firebase-to-excel:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write  # Necesario para hacer push
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Importante para poder hacer push después
        
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install firebase-admin pandas openpyxl

    - name: Debug - Mostrar secreto (solo para diagnóstico)
      run: |
        echo "Longitud del secreto: ${#FIREBASE_CREDENTIALS} caracteres"
        echo "Primeros 100 caracteres: ${FIREBASE_CREDENTIALS:0:100}"
        
    - name: Create Firebase credentials file
      run: |
        # Verifica que el secreto existe
        if [ -z "${{ secrets.FIREBASE_CREDENTIALS }}" ]; then
          echo "❌ Error: El secreto FIREBASE_CREDENTIALS está vacío o no existe"
          exit 1
        fi
        
        # Crea el archivo de forma segura
        echo '${{ secrets.FIREBASE_CREDENTIALS }}' > firebase_key.json
        
        # Verifica el archivo generado
        echo "=== Contenido del archivo (primeras líneas) ==="
        head -n 5 firebase_key.json
        echo "=== Verificación JSON ==="
        python -c "import json; json.load(open('firebase_key.json')); print('✓ JSON válido')" || exit 1
        
    - name: Run export script
      run: python firebase_export_automation.py
      
    - name: Commit and push changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add *.xlsx
        git commit -m "Automatic Firebase data update [skip ci]"
        git push
